### ISSUE TITLE
Error in path when executing migrations after 1.0.0-BETA1

### ISSUE THREAD

**Issue by Angelitorl** [tanoconsulting/ezmigrationbundle2#26]
Hello,

When updating the bundle to a more recent version (from [1.0.0-BETA1](https://github.com/tanoconsulting/ezmigrationbundle2/releases/tag/1.0.0-BETA1) to [1.0.3](https://github.com/tanoconsulting/ezmigrationbundle2/releases/tag/1.0.3)), we have found an error in the path definition when trying to execute the migrations.

## Actual Behavior
Considering that the development environment is *dockerized*, the current "project directory" is `var/www`. When trying to execute migration the following error is logged:

```
$bin/console kaliop:migration:migrate --path vendor/tanoconsulting/ezmigrationbundle/MigrationsDefinitions

In Filesystem.php line 112:
Path '/var/vendor/tanoconsulting/ezmigrationbundle/MigrationsDefinitions' is neither a file nor directory
``` 

As you can see, the path is not correct (`/var` instead of `/var/www`) . The same happens if we try to set the absolute path:

(`/var/var/www` instead of `/var/www`)
```
$bin/console kaliop:migration:migrate --path var/www/vendor/tanoconsulting/ezmigrationbundle/MigrationsDefinitions

In Filesystem.php line 112:                                         
Path '/var/var/www/vendor/tanoconsulting/ezmigrationbundle/MigrationsDefinitions' is neither a file nor directory 
```

We used as an example the documented migration from the vendor, but the same error occurs with the local migrations folder `src/MigrationsDefinitions`:

(`/var` instead of `/var/www`)
```
$bin/console kaliop:migration:migrate --path src/MigrationsDefinitions/20220101000200_FixExecutedMigrationsPaths.php  

In Filesystem.php line 112:
Path '/var/src/MigrationsDefinitions/20220101000200_FixExecutedMigrationsPaths.php' is neither a file nor directory 
```

## Origin

After some research, we've found that this change in behavior was originated in the following commit: https://github.com/kaliop-uk/ezmigrationbundle/commit/26788d71ad6a844ba0caad364b6cc8f7b32c2eb4. 

## Posible solution approach
We found that changing the following lines:
https://github.com/tanoconsulting/ezmigrationbundle2/blob/25b755daad21c6eb53261150eb3d302b7048d90a/Core/Loader/Filesystem.php#L82
https://github.com/tanoconsulting/ezmigrationbundle2/blob/25b755daad21c6eb53261150eb3d302b7048d90a/Core/Loader/Filesystem.php#L126

To:
```
$rootDir = realpath($this->kernel->getProjectDir()) . '/';
```
Solves the issue, but this solution is probably far from perfect.

**Comment by gggeek** [comment]
While I investigate the exact cause of the issue, there is one possible workaround which you might have overlooked: the code treats all migration paths starting with '/' as absolute.
You might have some success by using either

`$bin/console kaliop:migration:migrate --path /var/www/vendor/tanoconsulting/ezmigrationbundle/MigrationsDefinitions`

or

`$bin/console kaliop:migration:migrate --path $(pwd)/vendor/tanoconsulting/ezmigrationbundle/MigrationsDefinitions`

**Comment by gggeek** [comment]
So, this is what i think happened:
- when merging into ezmb2 all recent (at the time) changes of ezmb1, I made a mistake
- the merge was done manually, ie. by hand editing instead of advanced git blackmagic
- the mistake is the following: translating `$this->container->get('kernel')->getRootDir() . '/..'` into `$this->kernel->getProjectDir() . '/..'` - the latter does _not_ need the `/..` added to get the root of the Sf project

A small correction to your reporting: the issue started appearing in version 1.0.0-beta1, not afterwards. The commit with the mistake is c511b20fe1bc26946f16dc8ae1957be6bbd80656

As for the fix: your proposal is absolutely right!

If you want to send a PR, I'll gladly merge - just take care that there are 2 more files which need the same fix.

If you're busy and don't care about bragging rights, I can apply the same change by myself of course :-)

**Comment by gggeek** [comment]
Fixed with commit https://github.com/tanoconsulting/ezmigrationbundle2/commit/9e1d79f8a13f8277d9a29923fd9729aa0844fb90 - will be in rel. 1.0.4
